language: php

php:
  #- 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    
before_script: 
  - composer self-update
  - composer install --prefer-source --no-interaction
  - mkdir -p build/logs
  
script:
  - ./vendor/bin/phpunit -v -c phpunit.xml.dist --coverage-clover build/logs/clover.xml
  
after_script:
  # coveralls.io
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php vendor/bin/coveralls -v; fi
  # scrutinizer-ci
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8325a02313797dd6c619
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
